services:
  mongodb:
    container_name: mongodb
    image: mongo

  webstrates:
    container_name: webstrates
    build: .
    volumes:
      - ./uploads:/app/uploads
      - ./config.json:/app/config.json
    environment:
      - WEBSTRATES_DB=mongodb://mongodb:27017/webstrate
    ports:
      - 7007:7007
